title: Project

sections:
  content:
    type: fields
    fields:
      title:
        label: Title
        type: text
      date:
        label: Date
        type: date
        time: false
        default: today
      description:
        label: Description
        type: writer
      thumbnail:
        label: Image
        type: files
        max: 1
        uploads: project-file
