title: Site

sections:
  pages:
    type: pages

  artifacts:
    type: pages
    parent: site.find('artifacts')
    label: Artifacts
    sortBy: date desc
    create:
      - artifact
    templates:
      - artifact
    info: "{{ page.date.toDate('d-m-Y') }} | {{ page.tags }}"

  carousel:
    type: fields
    fields:
      homepageCarousel:
        label: Homepage carousel
        type: structure
        min: 3
        max: 5
        fields:
          title:
            label: Title
            type: text
          video:
            label: Video
            type: files
            multiple: false
            layout: cards
            uploads: true
            template: video
            max: 1
            accept: video/*
